# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XBoLv6zgBL5Q2BHULZGz7alAPCi9MQfe

===========================================================================
Project : Enterprise Procurement Analytics Platform
Module  : Configuration File

Description:
    Central configuration file for the data generation framework.

Author  : Ravi
Version : 1.0
===========================================================================
"""

from pathlib import Path

# =============================================================================
# Project Paths
# =============================================================================

# Project Root Directory
PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Data Directories
SOURCE_DATA_PATH = PROJECT_ROOT / "data" / "source"
LANDING_DATA_PATH = PROJECT_ROOT / "data" / "landing"
BRONZE_DATA_PATH = PROJECT_ROOT / "data" / "bronze"
SILVER_DATA_PATH = PROJECT_ROOT / "data" / "silver"
GOLD_DATA_PATH = PROJECT_ROOT / "data" / "gold"
REJECTED_DATA_PATH = PROJECT_ROOT / "data" / "rejected"

# =============================================================================
# Data Generation Configuration
# =============================================================================

NUMBER_OF_VENDORS = 5000

# =============================================================================
# Countries and Currency Mapping
# =============================================================================

COUNTRY_CURRENCY = {
    "India": "INR",
    "USA": "USD",
    "Germany": "EUR",
    "United Kingdom": "GBP",
    "Japan": "JPY"
}

# =============================================================================
# Vendor Categories
# =============================================================================

VENDOR_TYPES = [
    "Raw Material",
    "Packaging",
    "Electronics",
    "Industrial Equipment",
    "Logistics",
    "IT Equipment",
    "Maintenance Services",
    "Professional Services"
]

# =============================================================================
# Payment Terms
# =============================================================================

PAYMENT_TERMS = [
    "NET30",
    "NET45",
    "NET60",
    "ADVANCE",
    "IMMEDIATE"
]

# =============================================================================
# Vendor Status
# =============================================================================

ACTIVE_FLAG = ["Y", "N"]

# =============================================================================
# Random Seed
# =============================================================================

# Ensures reproducible data generation
RANDOM_SEED = 42

# =============================================================================
# Output Files
# =============================================================================

VENDOR_MASTER_FILE = SOURCE_DATA_PATH / "vendor_master.csv"